#!/bin/bash

# Install file for the Vim config


echo ""
echo "Installing Vim Config..."
echo ""

# Install
echo "----- Installing vim-plug"
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Install Plugins
echo ""
echo "----- Installing Plugins"
vim +PluginInstall +qall &

# Make directories for backups, swap, and undo files
echo ""
echo "----- Creating directories"
mkdir -p ~/.vim/undo ~/.vim/swap

# Expose the .vimrc file
echo ""
echo "----- Exposing .vimrc"
ln -s $HOME/.vim/.vimrc $HOME/.vimrc

# Finish installation
echo ""
echo "All done!"
echo ""
exit
